### ISSUE TITLE
Adapt To Builder API Changes

### ISSUE THREAD

**Issue by jdmaguire** [pravega/nautilus-samples#24] opened 2018-05-15 15:05 UTC
##### Issue 

Builder API https://github.com/pravega/flink-connectors/pull/125 removed and changed some classes. Need to update the samples's develop branch accordingly.

**Comment by vijikarthi** [comment] 2018-05-15 23:26
it's a duplicate of https://github.com/pravega/nautilus-samples/issues/20

**Closed by vijikarthi** 2018-05-15 23:26 UTC
